-- Run after migrations; all fixture changes are rolled back.
begin;
do $test$
declare login_a uuid; login_b uuid; worker_a uuid; worker_b uuid; project uuid; shift_a uuid; shift_b uuid; entry uuid; amount numeric; denied boolean; affected int;
begin
 select id into login_a from public.profiles order by created_at limit 1;
 select id into login_b from public.profiles where id<>login_a limit 1;
 if login_a is null or login_b is null then raise exception 'Two fixture logins required'; end if;
 update public.profiles set role='shop' where id in(login_a,login_b);
 select id into project from public.bids where status='won' and completed_at is null limit 1;
 insert into public.shop_workers(login_id,first_name,last_name) values(login_a,'Clock','Tester') returning id into worker_a;
 insert into public.shop_workers(login_id,first_name,last_name) values(login_a,'Second','Worker') returning id into worker_b;
 perform set_config('request.jwt.claim.sub',login_a::text,true);
 execute 'set local role authenticated';
 denied:=false;
 begin perform public.start_shop_shift(worker_a,project,'Test','invalid',false); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Invalid category accepted'; end if;
 shift_a := public.start_shop_shift(worker_a,project,'Test','field',true);
 shift_b := public.start_shop_shift(worker_b,project,null);
 denied:=false;
 begin perform public.start_shop_shift(worker_a,project,null); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Duplicate shift accepted'; end if;
 execute 'reset role';
 update public.shop_shifts set started_at=clock_timestamp()-interval '90 minutes' where id=shift_a;
 perform set_config('request.jwt.claim.sub',login_b::text,true);
 execute 'set local role authenticated';
 denied:=false;
 begin perform public.stop_shop_shift(shift_a); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Cross-login clock-out accepted'; end if;
 denied:=false;
 begin perform public.start_shop_shift(worker_a,project,null); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Cross-login clock-in accepted'; end if;
 perform set_config('request.jwt.claim.sub',login_a::text,true);
 entry:=public.stop_shop_shift(shift_a);
 if public.stop_shop_shift(shift_a)<>entry then raise exception 'Clock-out is not idempotent'; end if;
 update public.time_entries set hours=9 where id=entry;
 get diagnostics affected=row_count;
 if affected<>0 then raise exception 'Shop can edit time'; end if;
 execute 'reset role';
 select hours into amount from public.time_entries where id=entry;
 if amount<>1.5 then raise exception 'Incorrect elapsed hours: %',amount; end if;
 if not exists(select 1 from public.time_entries where id=entry and kind='field' and night=true) then raise exception 'Install/night settings were not saved'; end if;
 if not exists(select 1 from public.shop_shifts where id=shift_b and kind='shop' and night=false) then raise exception 'Legacy clock defaults changed'; end if;
 if not exists(select 1 from public.shop_shifts where id=shift_b and ended_at is null) then raise exception 'Switching worker stopped other shift'; end if;
 update public.shop_workers set active=false where id=worker_b;
 perform set_config('request.jwt.claim.sub',login_a::text,true);
 execute 'set local role authenticated';
 perform public.stop_shop_shift(shift_b);
 denied:=false;
 begin perform public.start_shop_shift(worker_b,project,null); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Inactive worker can start shift'; end if;
 execute 'reset role';
end $test$;
rollback;
